### ISSUE TITLE
Error when training with adaface's training set

### ISSUE THREAD

**Issue by Edgar-Lzxc** [liuf1990/CFSM#5]

**Comment by Edgar-Lzxc** [comment]
torch.Size([12000, 3, 112, 112])
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main(parser.parse_args())
  File "train.py", line 135, in main
    updated_img, updated_local_labels = adversarial_regu.adversarial_img_augmentation(cfg, syn_model, backbone, module_partial_fc, img, local_labels, opt)
  File "/home/myuser/PycharmProjects/GuidedFaceRecognition/adversarial_regu.py", line 19, in adversarial_img_augmentation
    loss: torch.Tensor = module_partial_fc(local_embeddings, local_labels, opt)
  File "/home/myuser/.conda/envs/adaface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/myuser/PycharmProjects/GuidedFaceRecognition/partial_fc.py", line 212, in forward
    logits = self.margin_softmax(logits, labels)
  File "/home/myuser/.conda/envs/adaface/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/myuser/PycharmProjects/GuidedFaceRecognition/losses.py", line 63, in forward
    safe_norms = torch.clip(norms, min=0.001, max=100) # for stability
TypeError: clip() received an invalid combination of arguments - got (NoneType, max=int, min=float), but expected one of:
 * (Tensor input, Tensor min, Tensor max, *, Tensor out)
 * (Tensor input, Number min, Number max, *, Tensor out)

**Comment by Edgar-Lzxc** [comment]
config.loss = "adaface"
config.output = "arcface_ms1mv2_r101_ours"
config.network = "r100"
config.resume = False
config.pretrained_backbone_model = None
config.pretrained_partial_fc_path = None
config.embedding_size = 512
config.sample_rate = 1.0
config.fp16 = True
config.momentum = 0.9
config.weight_decay = 5e-4
config.batch_size = 64
config.lr = 0.1
config.verbose = 2000
config.dali = False
config.frequent = 10
config.score = None

config.rec = "faces_megafacetrain_112x112"
# config.num_classes = 85742
config.num_classes =657078
# config.num_image = 3870313
config.num_image = 4574213
config.num_epoch = 20
config.warmup_epoch = 2
config.val_targets = ["lfw", "cfp_fp","cfp_ff", "agedb_30"]


config.rs_ratio = 0.75
config.pretrained_synthesis_model = "pretrained/WiderFace70K.pth"
config.epsilon = 0.314   
config.alpha = 0.314     
config.k = 1
